### ISSUE TITLE
Input data format - pleaase provide data file with few entries

### ISSUE THREAD

**Issue by Deven207** [pinkeshbadjatiya/movie-recommendation-using-RBM#1]
I am not able to understand the format of data. Can you add text file which have 5 entries so I can understand how data are stored and processing. 

Thanks in advance !!

**Comment by pinkeshbadjatiya** [comment]
It accepts the dataset in the same format as mentioned in the paper. Request you to go through it once.

**Comment by Deven207** [comment]
Thanks

Regards,
Deven
