### ISSUE TITLE
model.py setW() bug?

### ISSUE THREAD

**Issue by shitian-ni** [pinkeshbadjatiya/movie-recommendation-using-RBM#3]
Line 65, `self.w[:, m, :] += w[:, it, :]` should be `self.w[:, m, :] = w[:, it, :]`?
Addition already done in `train `, and loss result incorrect if use `+=`

Loss if use `+=`
![plus_equal](https://user-images.githubusercontent.com/20103571/42682487-aedab706-86c5-11e8-9e8e-2adacff01253.png)
Loss if use `=`
![equal](https://user-images.githubusercontent.com/20103571/42682508-c0c799a2-86c5-11e8-86a5-ee986d26a498.png)

**Comment by pinkeshbadjatiya** [comment]
Yes, it looks like what you suggest is in fact correct.
